
[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  branch = "master"
  name = "github.com/function61/eventhorizon"

[[constraint]]
  branch = "master"
  name = "github.com/mattetti/filebuffer"

[[constraint]]
  branch = "master"
  name = "github.com/tobischo/gokeepasslib"

[[constraint]]
  # need to track master, because while this project has tagged releases,
  # they are wildly out of date
  branch = "master"
  name = "github.com/pquerna/otp"

[prune]
  go-tests = true
  unused-packages = true
