
[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  branch = "master"
  name = "github.com/function61/eventhorizon"

[[constraint]]
  branch = "master"
  name = "github.com/mattetti/filebuffer"

[[constraint]]
  branch = "master"
  name = "github.com/tobischo/gokeepasslib"

[prune]
  go-tests = true
  unused-packages = true
