site_name: 'pi-security-module docs'

theme: readthedocs

docs_dir: '.'

pages:

- 'index.md'

- 'For users':
  - 'Command line': 'user-guides/command-line.md'
  - 'Comparison to alternatives': 'user-guides/comparison-to-alternatives.md'
  
- 'General':
  - 'Architecture': 'architecture.md'
  - 'Internal dependencies': 'internal-dependencies.md'

- 'Domain model':
  - 'Events': 'domain/events.md'
  - 'Types': 'domain/types.md'

- 'Data API (REST)':
  - 'Types': 'apitypes/types.md'
  - 'Commands (for writing data)': 'commands/commands.md'
  - 'Endpoints (for reading data)': 'apitypes/rest_endpoints.md'

- 'Signing API (REST)':
  - 'Types': 'signingapi/types.md'
  - 'Endpoints': 'signingapi/rest_endpoints.md'
