site_name: 'pi-security-module docs'

theme: readthedocs

docs_dir: '.'

pages:

- 'index.md'

- 'For users':
  - 'Command line': 'user-guides/command-line.md'
  - 'Comparison to alternatives': 'user-guides/comparison-to-alternatives.md'
  
- 'General':
  - 'Architecture': 'architecture.md'
  - 'Internal dependencies': 'internal-dependencies.md'

- 'Domain model':
  - 'Events': 'domain_model/events.md'
  - 'Constants and enums': 'domain_model/consts-and-enums.md'

- 'Application model (REST API)':
  - 'Queries (for reading data)': 'application_model/rest_endpoints.md'
  - 'Commands (for writing data)': 'application_model/commands.md'
